name: E2E

on:
  push:
    branches:
      - main

jobs:
  frameworks:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        directory:
          - one-two
          - one
          - two
        include:
          - directory: one
          - directory: two
    name: Lorem / ${{ matrix.directory }} / Python ${{ matrix.python-version }} 
    defaults:
      run:
        working-directory: e2e/${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install build tools
        run: |
            python -m pip install -U pip==23.3.1
        shell: bash
      # Using approach described here for Python location caching:
      # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
      - name: Cache Python location
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: pythonloc-${{ matrix.directory }}-${{ env.pythonLocation }}-${{ hashFiles('./e2e/*/pyproject.toml') }}
      - name: Install dependencies
        run: python -m pip install --upgrade .
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"