name: Cache cleanup
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - directory: one
          - directory: two
    name: Lorem / ${{ matrix.directory }}
    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Cleanup caches by directories
        # Only keep caches that match the latest keys
        run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge
          LATEST_KEY=pythonloc-${{ matrix.directory }}-${{ env.pythonLocation }}-${{ hashFiles(format('./e2e/{0}/pyproject.toml', matrix.directory)) }}

          echo "Fetching list of cache keys"
          cacheKeys=$(gh actions-cache list -R $REPO | grep "${{matrix.directory}}" | cut -f 1 )

          echo "$cacheKeys"

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
            if [ "$cacheKey" != "$LATEST_KEY" ]; then
              echo -e "\tOld key found -> $cacheKey"
              echo -e "\tWill run -> gh actions-cache delete "$cacheKey" --confirm"
            fi
          done

          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
